routes/web.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::resource('users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $fillable = [
        'firstname' , 'lastname' , 'image' , 'city' , 'age'
    ];

    public function getImagePathAttribute(){
        return '/image/users/' . $this->image;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        return  view('user.index',compact('users'));
    }


    public function create()
    {
        return view('user.create');
    }

    public function store(Request $request)
    {
        $request->validate(array_merge($this->rules(),['image' => 'required | image']));
        $user = new User();
        $user->firstname = $request->firstname;
        $user->lastname = $request->lastname;
        $user->city = $request->city;
        $user->age = $request->age;

        if ($request->hasFile('image')){
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('/image/users', $filename,'public');
            $user->image = $filename;
        }
        $user->save();
        return redirect()->route('users.index')->with('success','User created successfully');
    }


    public function edit(User $user)
    {
        return view('user.edit',compact('user'));
    }


    public function update(Request $request, User $user)
    {

        $request->validate($this->rules());
        $user->firstname = $request->firstname;
        $user->lastname = $request->lastname;
        $user->city = $request->city;
        $user->age = $request->age;

        if ($request->hasFile('image')){
            $image = $request->file('image');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $image->storeAs('/image/users', $filename,'public');
            $user->image = $filename;
        }
        $user->save();
        return redirect()->route('users.index')->with('success','User updated successfully');
    }


    public function destroy(User $user)
    {
        $completeImagePath = public_path() . $user->imagePath;
        if (File::exists($completeImagePath)){
            File::delete($completeImagePath);
        }
        $user->delete();
        return redirect()->route('users.index')->with('success','User deleted successfully');
    }

    private function rules(){
        $rules = [
            'firstname' => 'required | max:255',
            'lastname' => 'required | max:255',
            'city' => 'required | max:255',
            'age' => 'required | integer | lt:200',
        ];
        return $rules;
    }
}

resources/views/index.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="container mt-3">
        <p>This is Crud User application, You Can use top navigation to see list of users or create User,</p>
        <p>From list of user you can delete and edit user</p>
    </div>
@endsection

resources/views/layouts/frontend.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>User Crud Project</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{{URL::to('/')}}">User Crud Application</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="{{route('users.index')}}">Users List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('users.create')}}">Create User</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container py-3 bg-light mt-3">
    <p class="mb-0 "><strong>My name is: Saeed Rashid, My Student id: 98221033111022</strong></p>
</div>
@yield('content')

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
-->
</body>
</html>

resources/views/user/create.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="content my-4">
        <div class="container">
            <div class="heading text-center my-4">
                <h1>Create User</h1>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{route('users.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row mb-3">
                    <div class="col">
                        <input type="text" name="firstname" class="form-control" placeholder="First name" value="{{ old('firstname') }}">
                    </div>
                    <div class="col">
                        <input type="text" name="lastname" class="form-control" placeholder="Last name" value="{{ old('lastname') }}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <input type="text" name="city" class="form-control" placeholder="City" value="{{ old('city') }}">
                    </div>
                    <div class="col">
                        <input type="text" name="age" class="form-control" placeholder="Age" value="{{ old('age') }}">
                    </div>
                </div>
                <div class="mb-3">
                    <label for="formFile" class="form-label">Image</label>
                    <input name="image" class="form-control" type="file" id="formFile">
                </div>
                <button type="submit" class="btn btn-primary w-100">Create</button>
            </form>
        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="content my-4">
        <div class="container">
            <div class="heading text-center my-4">
                <h1>Update User</h1>
            </div>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form action="{{route('users.update', $user->id)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row mb-3">
                    <div class="col">
                        <input type="text" name="firstname" class="form-control" placeholder="First name"
                               value="{{ old('firstname') ?: $user->firstname }}">
                    </div>
                    <div class="col">
                        <input type="text" name="lastname" class="form-control" placeholder="Last name"
                               value="{{ old('lastname') ?: $user->lastname }}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <input type="text" name="city" class="form-control" placeholder="City"
                               value="{{ old('city') ?: $user->city }}">
                    </div>
                    <div class="col">
                        <input type="text" name="age" class="form-control" placeholder="Age"
                               value="{{ old('age') ?: $user->age }}">
                    </div>
                </div>
                <img height="100" width="300" src="{{$user->imagePath}}" alt="" class="img-thumbnail mb-3">
                <div class="mb-3">
                    <label for="formFile" class="form-label">To change image upload new one</label>
                    <input name="image" class="form-control" type="file" id="formFile">
                </div>
                <button type="submit" class="btn btn-primary w-100">update</button>
            </form>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="content my-4">
        <div class="container">
            <div class="heading text-center my-4">
                <h1>Users List</h1>
            </div>
            @if(Session::has('success'))
                <p class="alert alert-success">{{ Session::get('success') }}</p>
            @endif
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Image</th>
                    <th scope="col">City</th>
                    <th scope="col">Age</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                <tr>
                    <th scope="row">{{$user->id}}</th>
                    <td>{{$user->firstname}}</td>
                    <td>{{$user->lastname}}</td>
                    <td><img  height="50" src="{{$user->imagePath}}" alt=""></td>
                    <td>{{$user->city}}</td>
                    <td>{{$user->age}}</td>
                    <td>
                        <a href="{{route('users.edit',$user->id)}}" class="btn">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                            </svg>
                        </a>
                        <form action="{{route('users.destroy',$user->id)}}" method="post" class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button class="btn">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </button>
                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection